
include("empty.jl")
include("normalization.jl")
include("aggregate_scaling.jl")
include("rate_synapse.jl")
include("fl_synapse.jl")
include("fl_sparse_synapse.jl")
include("pinning_synapse.jl")
include("pinning_sparse_synapse.jl")
include("spike_rate_synapse.jl")
include("sparse_plasticity.jl")
include("spiking_synapse.jl")
